name: Scala

on:
  pull_request: {}
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java:
          - jdk11
    steps:
      - uses: actions/checkout@v2.3.2

      - name: "Cache for sbt & coursier ♨️"
        uses: coursier/cache-action@v4.1

      - name: "Install Nix ❄️"
        uses: cachix/install-nix-action@v12

      - name: "Install Cachix ❄️"
        uses: cachix/cachix-action@v8
        with:
          name: neutron
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"

      - name: "Run with ${{ matrix.java }} 🚀"
        run: nix-shell --argstr jdk "${{ matrix.java }}" --run "sbt compile" nix/ci.nix
